
################# ollama.yml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ollama
spec:
  selector:
    matchLabels:
      app: ollama
  replicas: 1 # tells deployment to run 1 pods matching the template
  template:
    metadata:
      labels:
        app: ollama
    spec:
      containers:
      - name: ollama
        image: maadsdocker/tml-privategpt-with-gpu-nvidia-amd64-llama3-tools # IF you DO NOT have NVIDIA GPU then CPU will be used
        imagePullPolicy: IfNotPresent  # You can also use Always, Never
        env:
        - name: NVIDIA_VISIBLE_DEVICES
          value: all
        - name: DP_DISABLE_HEALTHCHECKS
          value: xids
        - name: WEB_CONCURRENCY
          value: ""
        - name: GPU
          value: "1"
        - name: COLLECTION
          value: "tml-llm-model-v2"
        - name: PORT
          value: "11434"
        - name: CUDA_VISIBLE_DEVICES
          value: "0"
        - name: TOKENIZERS_PARALLELISM
          value: "false"
        - name: temperature
          value: "0.1"
        - name: rollbackoffset
          value: "15"
        - name: ollama-model
          value: "phi3:3.8b,phi3:3.8b,llama3.2:3b"
        - name: deletevectordbcount
          value: "5"
        - name: vectordbpath
          value: "/rawdata/vectordb"
        - name: topicid
          value: "-999"
        - name: enabletls
          value: "1"
        - name: partition
          value: "-1"
        - name: vectordbcollectionname
          value: "tml-llm-model-v2"
        - name: ollamacontainername
          value: "maadsdocker/tml-privategpt-with-gpu-nvidia-amd64-llama3-tools"
        - name: mainip
          value: "http://127.0.0.1"
        - name: mainport
          value: "11434"
        - name: embedding
          value: "nomic-embed-text"
        - name: agents_topic_prompt
          value: "iot-preprocess<<-You are a precise data analysis assistant. Your task is to point out any anomalies or interesting insights that could help improve the performance and functioning of         IoT device.  The json data are from IOT devices.  the hp field shows the data that are processed for the process variable (pv), using the process types (pt) like:         avg or average, or trend analysis, or anomprob (i.e. anomaly probability) etc.  The device being processed is in the uid field of the json.         here is the json data:              <<data>>         INSTRUCTIONS:         1. Examine each number in the json array         2. Provide a brief analysis of the results                  FORMAT YOUR RESPONSE:         - Filtered results: [list the qualifying numbers with their "uid" fields]         - Count of qualifying numbers: [number]         - Analysis: [brief explanation of what the filter revealed]                  Be precise and concise in your response.->>        iot-ml-prediction-results-output<<-You are a precise data analysis assistant. Your task is to filter and analyze numeric data based on specified criteria.        TASK: Filter numbers from the given json array using the threshold: greater than 90        Input JSON arrary:              <<data>>         INSTRUCTIONS:         1. Examine each number in the json array         2. Apply the filter condition: number > 90         3. Return only numbers that meet the criteria with their "uid" fields         4. If no numbers meet the criteria, explicitly state this         5. Provide a brief analysis of the results                  FORMAT YOUR RESPONSE:         - Filtered results: [list the qualifying numbers with their "uid" fields]         - Count of qualifying numbers: [number]         - Analysis: [brief explanation of what the filter revealed]                  Be precise and concise in your response."
        - name: teamlead_topic
          value: "team-lead-responses"
        - name: teamleadprompt
          value: "Analyze the dataset containing IoT device monitoring records managed by individual agents.           Review all data fields to determine whether there are any issues or major concerns requiring urgent attention.           Focus on the following criteria:          1. Each record contains a unique device identifier stored in the field "uid".          2. Examine the failure probability for each device stored in the hp field.          3. Categorize the probabilities as follows:           - Low: 0% to 50%           - Medium: 51% to 75%           - High: 76% to 89%           - Urgent: 90% to 100%          Tasks:         - Identify and highlight devices (by their "uid") that have **urgent failure probabilities** (≥ 90%).         - For each flagged device, provide details and reasoning on why it may require immediate investigation.         - Only include devices that meet the urgent threshold. Do not report on low, medium, or high categories unless relevant for context.         - State clearly whether the identified issue is *urgent*.         - Do not use or generate any code, perform a reasoning-based analysis directly from the provided data."
        - name: supervisor_topic
          value: "supervisor-responses"
        - name: supervisorprompt
          value: "You are a team supervisor analyzing operational device data and recommending whether an alert email should be send.          You manage a send email expert and a average expert.         For send email, use send_email agent.         For average, use average agent.       INSTRUCTIONS:       1.Analyze the Team Lead assessment and determine the proper action:       - If devices are marked urgent or failure probabilities exceed 90%, select "send_email".       - If no urgent devices are found or probabilities remain below thresholds, then no action is needed."
        - name: agenttoolfunctions
          value: "send_email<<-send_email<<- You are an email-sending agent. Use smtp parameters to send emails when there is an anomaly in the data, make sure to                     indicate the device name in the mainuid field. do not write a smtp script, actually send the email using the SMTP parameters                     smtp_server=smtp.gmail.com                     smtp_port=587                     username=sebastian.maurice@gmail.com                     password=                     sender=sebastian.maurice@gmail.com                     recipient=sebastian.maurice@otics.ca,sebastian.maurice@gmail.com,smaurice@firstgenesis.com                     subject=                     body=->>        average<<-average<<-You are an average agent.  Take average of the device failure probabilities."
        - name: agent_team_supervisor_topic
          value: "all-agents-responses"
        - name: contextwindow
          value: "4096"          
        - name: TSS
          value: "0"
        - name: KUBE
          value: "1"
        resources:             # REMOVE or COMMENT OUT: IF you DO NOT have NVIDIA GPU
          limits:              # REMOVE or COMMENT OUT: IF you DO NOT have NVIDIA GPU
            nvidia.com/gpu: 1  # REMOVE or COMMENT OUT: IF you DO NOT have NVIDIA GPU
        ports:
        - containerPort: 11434
      tolerations:             # REMOVE or COMMENT OUT: IF you DO NOT have NVIDIA GPU
      - key: nvidia.com/gpu    # REMOVE or COMMENT OUT: IF you DO NOT have NVIDIA GPU
        operator: Exists       # REMOVE or COMMENT OUT: IF you DO NOT have NVIDIA GPU
        effect: NoSchedule     # REMOVE or COMMENT OUT: IF you DO NOT have NVIDIA GPU
---
apiVersion: v1
kind: Service
metadata:
  name: ollama-service
  labels:
    app: ollama-service
spec:
  type: NodePort #Exposes the service as a node ports
  ports:
  - port: 11434
    name: p1
    protocol: TCP
    targetPort: 11434
  selector:
    app: ollama
